export enum NotificationType {
  MONEY_SENT = 'MONEY_SENT',
  MONEY_RECEIVED = 'MONEY_RECEIVED',
  CARD_ADDED = 'CARD_ADDED',
  CARD_FROZEN = 'CARD_FROZEN',
  BENEFICIARY_ADDED = 'BENEFICIARY_ADDED',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  SECURITY = 'SECURITY',
}